name: Build and Push Container Image

on:
  workflow_run:
    workflows: ["Build .Net"]
    types:
      - completed
    branches:
      - main
      - rc

permissions:
  contents: write
  packages: write
  repository-projects: write

jobs:
  build:
    uses: codedesignplus/workflows/.github/workflows/container-image.yaml@main
    with:
      project-name: CodeDesignPlus.Net.Microservice.Roles
      microservice-name: ms-roles
    secrets: inherit